import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Header from "@/components/Header/Header";
import ProviderWrapper from "@/Store/provider";



const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Imagination",
  description: "Generated by create next app",
  icons: './icon.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderWrapper>
            <Header />
            <main className="wrapper">
              {children}
            </main>
        </ProviderWrapper>
          
      </body>
    </html>
  );
}
